# Generated by Django 3.2.9 on 2021-12-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('category', models.IntegerField(choices=[(1, 'DAILY ACTIVITIES'), (2, 'SCIENCE'), (3, 'HOBBY'), (4, 'SPORT'), (5, 'MOTORSPORT'), (6, 'COOKING')])),
            ],
        ),
    ]
