# Generated by Django 3.2.9 on 2021-12-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoonPlanApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.CharField(max_length=64)),
                ('attendees', models.ManyToManyField(blank=True, to='MoonPlanApp.Activity')),
            ],
        ),
    ]
